project_id = "funtime-t3-local"

[api]
enabled = true
port = 55421
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 55422
shadow_port = 55420
major_version = 15

[db.pooler]
enabled = false

[db.seed]
enabled = false
sql_paths = ["./seed.sql"]

[realtime]
enabled = true

[studio]
enabled = true
port = 55423
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 55424
smtp_port = 55425
pop3_port = 55426

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = [
  "http://127.0.0.1:3000",
  "http://localhost:3000",
  "exp://127.0.0.1:8081",
  "exp://localhost:8081",
]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false

[edge_runtime]
enabled = true

[analytics]
enabled = false
