# fly.toml app configuration file generated for funtime-cron-2 on 2024-06-30T22:13:50-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "funtime-cron-2"
primary_region = "bos"
